### ISSUE TITLE
#4: Hide unborrowable assets from the borrow modal dropdown

### ISSUE THREAD

**Issue by 4c6961** [Agave-DAO/frontend-v2#4]
While in borrow modal view, we can switch to other assets. The list contains all assets but the unborrowable ones should be excluded.

**Comment by Luigy-Lemon** [comment]
The dropdown list does hide unborrowable assets in the borrow modal but once switched into repay mode the list does not include the unborrowable assets. Instead it should list the assets a user has borrows at... including frozen and currently unborrowable assets.

**Comment by Luigy-Lemon** [comment]
https://github.com/Agave-DAO/frontend-v2/commit/73590c295e28b5e34bb7d93557fd5c976a942b07
